NutritionProject/NutritionProject/NutritionProject/Controllers/ChronicDiseaseController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NutritionProject.Controllers
{
    public class ChronicDiseaseController : Controller
    {
        ChronicDiseaseManager cdm = new ChronicDiseaseManager(new EfChronicDiseaseDal());

        public ActionResult Index()
        {
            var diseasevalues = cdm.GetList();
            return View(diseasevalues);
        }

        [HttpGet]
        public ActionResult AddChronicDisease()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddChronicDisease(ChronicDisease p)
        {
            cdm.ChronicDiseaseAdd(p);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult EditChronicDisease(int id)
        {
            var diseasevalues = cdm.GetByID(id);
            return View(diseasevalues);
        }

        [HttpPost]
        public ActionResult EditChronicDisease(ChronicDisease p)
        {
            cdm.ChronicDiseaseUpdate(p);
            return RedirectToAction("Index");
        }
        public ActionResult DeleteChronicDisease(int id)
        {
            var diseasevalues = cdm.GetByID(id);
            cdm.ChronicDiseaseDelete(diseasevalues);
            return RedirectToAction("Index");

        }
    }
}

NutritionProject/NutritionProject/NutritionProject/Views/ChronicDisease/AddChronicDisease.cshtml
@model EntityLayer.Concrete.ChronicDisease
@{
    ViewBag.Title = "AddChronicDisease";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h1>Yeni Kronik Hastalık Ekleme Sayfası</h1>
<br />
@using (Html.BeginForm("AddChronicDisease", "ChronicDisease", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Kronik Hastalık Adı")
        @Html.TextBoxFor(x => x.ChronicDiseaseName, new { @class = "form-control" })
        <br /> <br />
        <button class="btn btn-info">Kaydet</button>
    </div>
}

NutritionProject/NutritionProject/NutritionProject/Views/ChronicDisease/EditChronicDisease.cshtml
@model EntityLayer.Concrete.ChronicDisease
@{
    ViewBag.Title = "EditChronicDisease";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />
<h2>Kronik Hastalık Güncelleme Sayfası</h2>
@using (Html.BeginForm("EditChronicDisease", "ChronicDisease", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Kronik Hastalık ID")
        @Html.TextBoxFor(x => x.ChronicDiseaseID, new { @class = "form-control" })
        <br />
        @Html.Label("Kronik Hastalık Adı")
        @Html.TextBoxFor(x => x.ChronicDiseaseName, new { @class = "form-control" })
        <br />
        <button class="btn btn-success">Güncelle</button>
    </div>
}

NutritionProject/NutritionProject/NutritionProject/Views/ChronicDisease/Index.cshtml
@using EntityLayer.Concrete
@model List<ChronicDisease>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br />

<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Kronik Hastalık Adı</th>
        <th>Sil</th>
        <th>Güncelle</th>


    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <th>@item.ChronicDiseaseID</th>
            <td>@item.ChronicDiseaseName</td>
            <td><a href="/ChronicDisease/DeleteChronicDisease/@item.ChronicDiseaseID" class="btn btn-danger">Sil</a></td>
            <td><a href="/ChronicDisease/EditChronicDisease/@item.ChronicDiseaseID" class="btn btn-warning">Güncelle</a></td>

        </tr>
    }


</table>
<a href="/ChronicDisease/AddChronicDisease" class="btn btn-info">Yeni Kronik Hastalık Ekle</a>